### ISSUE TITLE
Values from BME688 module are getting smaller with each measurement

### ISSUE THREAD

**Issue by marcinulan** [KitronikLtd/Kitronik-Raspberry-Pi-Air-Quality-Control-HAT-Python#2]
I have a simple Flask app. 

1. I start the app, there is an initial measurement
2. Every 20s there is a new measurement

Expected result: every measurement have similar values, as outside environment isn't changing

Actual result: with each new measurement I see smaller values (indicating cleaner air)

My code:

> from time import sleep
> from KitronikAirQualityControlHAT import *
> from flask import Flask, request, jsonify
> from flask_apscheduler import APScheduler
> 
> app = Flask(__name__)
> 
> scheduler = APScheduler()
> scheduler.api_enabled = True
> scheduler.init_app(app)
> 
> bme688 = KitronikBME688()
> oled = KitronikOLED()
> bme688.calcBaselines(oled)
> 
> print("____ Listening for requests _____")
> 
> @scheduler.task('interval', id='update_sensors', seconds=20, misfire_grace_time=900)
> def update_sensors():
>         print("…Updating sensors… please wait")
>         bme688.measureData()
>         global quality
>         quality = update_quality(bme688)
>         global co2
>         co2 = update_co2(bme688)
>         print("Sensors were updated.")
> 
> def update_quality(bme688):
>         quality = bme688.getAirQualityPercent()
>         print("Updating Air Quality value… Now it is", quality, "%")
>         return quality
> 
> def update_co2(bme688):
>         co2 = bme688.readeCO2()
>         print("Updating CO2 level value… Now it is", co2)
>         return co2
> 
> @app.get("/show")
> def show():
>         print("Temperature:", bme688.readTemperature())
>         print("Pressure:", bme688.readPressure()/100, " hPa")
>         print("Humidity:", bme688.readHumidity())
>         print("eCO2:", bme688.readeCO2())
>         print("Air Quality %:", bme688.getAirQualityPercent())
>         print("Air Quality Score:", bme688.getAirQualityScore())
>         resp = jsonify(success=True)
>         return resp
> 
> update_sensors()
> scheduler.start()
> print("Temperature:", bme688.readTemperature())
> print("Pressure:", bme688.readPressure()/100, " hPa")
> print("Humidity:", bme688.readHumidity())
> print("eCO2:", bme688.readeCO2())
> print("Air Quality %:", bme688.getAirQualityPercent())
> print("SENSORS ARE READY!!!")
> 
> @app.get("/quality")
> def get_quality():
>         print("Processing a GET")
>         return jsonify(quality)
> 
> @app.get("/co2")
> def get_CO2():
>         print("Processing a GET")
>         return jsonify(co2)
> 
> if __name__ == '__basic__':
>    app = create_app()
>    app.run(host='0.0.0.0', port=5000, debug = True)

Results from the app:

![image](https://github.com/KitronikLtd/Kitronik-Raspberry-Pi-Air-Quality-Control-HAT-Python/assets/13141685/75785937-04c6-48b4-aba2-b985d4596996)

**Comment by marcinulan** [comment]
OK, I see that after some time, readings are stabilizing. Maybe it is just how this works. Can be closed.

**Comment by KitronikLtd** [comment]
The general opinion is that it can take around 24 hours for the sensor to stabilise to the environment around it. By the looks of it this is what you have seen, glad it is now working for you.
